"""
Student Model Module.

This module defines two Pydantic models for the Student entity:

  - Student_model          : Used as the REQUEST body shape (client → server).
                             Contains only name, age, and city — no id field.
                             The id is NOT accepted from the client because it is always
                             auto-generated by the database on insertion.

  - Student_response_model : Used as the RESPONSE body shape (server → client).
                             'id' is always a required int because the database always
                             assigns it before the server sends the response back.

Separating request and response models is a best practice because:
  1. It makes the API contract explicit — callers know exactly what to send vs. what they get back.
  2. It prevents leaking internal/optional fields (like a None id) into responses.
  3. FastAPI/Pydantic can generate cleaner OpenAPI docs for each direction.
"""

from pydantic import BaseModel, Field, EmailStr



class Student_model(BaseModel):
    """
    Represents the REQUEST body shape for Student operations.

    Used when the CLIENT sends data to the server (e.g., POST /students request body).
    The 'id' field is intentionally absent — the client has no role in assigning it.
    The database auto-generates the id on every insertion.

    Attributes:
        name (str): The full name of the student.
        age (int): The age of the student.
        city (str): The city where the student resides.
        email (EmailStr): The email address of the student.
    """
    name: str = Field(..., description="Full name of the student.", min_length=1, max_length=100)
    age: int = Field(..., description="Age of the student.", ge=0)
    city: str = Field(..., description="City where the student resides.", min_length=1, max_length=100)
    email: EmailStr = Field(..., description="Email address of the student.")


class Student_response_model(BaseModel):
    """
    Represents the RESPONSE body shape for Student operations.

    Used when the SERVER sends data back to the client (e.g., GET/POST responses).
    The 'id' field is always a required integer here because by the time the server
    responds, the student has already been persisted and has a database-assigned ID.

    Attributes:
        id (int): The unique, database-assigned identifier for the student.
        name (str): The full name of the student.
        age (int): The age of the student.
        city (str): The city where the student resides.
        email (EmailStr): The email address of the student.
    """
    id: int = Field(description="Unique, database-assigned identifier for the student.")
    name: str = Field(description="Full name of the student.", min_length=1, max_length=100)
    age: int = Field(description="Age of the student.", ge=0)
    city: str = Field(description="City where the student resides.", min_length=1, max_length=100)
    email: EmailStr = Field(description="Email address of the student.")
